service: sls-notes-backend

provider:
  name: aws
  runtime: nodejs14.x  # Corrected runtime to a valid value
  region: ap-southeast-2
  stage: prod
  memorySize: 128
  timeout: 5
  endpointType: regional  # Corrected the typo in endpointType
  environment:
    NOTES_TABLE: ${self:service}-${opt:stage, self:provider.stage}

resources:
  Resources:
    NotesTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.NOTES_TABLE}
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S  # Corrected AttributeType to String (S)
          - AttributeName: timestamp
            AttributeType: N
          - AttributeName: note_id
            AttributeType: S  # Corrected AttributeType to String (S)
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: note_id-index
            KeySchema:
              - AttributeName: note_id  # Corrected AttributeName to note_id
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
