service: sls-notes-backend

useDotenv: true

plugins:
  - serverless-offline
  - serverless-add-api-key
  - serverless-dotenv-plugin

custom:
  allowedHeaders:
    - accept
    - Content-Type
    - Content-Length
    - Authorization
    - X-Amz-Date
    - X-Api-Key
    - X-Amz-Security-Token
    - X-Amz-User-Agent
    - app_user_id
    - app_user_name


provider:
  name: aws
  runtime: nodejs14.x  # Corrected runtime to a valid value
  region: ap-southeast-2
  stage: prod
  memorySize: 128
  timeout: 5
  endpointType: regional  # Corrected the typo in endpointType
  environment:
    DB_HOST: ${env:DB_HOST}
  
functions:
  add-note:
    handler: api-mongodb/add-note.handler
    description: POST /note
    events:
      - http:
          path: note
          method: post
          cors: 
            origin: '*'
            headers: ${self:custom.allowedHeaders}
  